#!/bin/sh

PROJ_ROOT=$(dirname $0)/..
DIR_LIB=$PROJ_ROOT/lib

mkdir -p $DIR_LIB

wget http://search.maven.org/remotecontent?filepath=junit/junit/4.12/junit-4.12.jar -O $DIR_LIB/junit.jar
wget http://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar -O $DIR_LIB/hamcrest-core.jar
